name = "Hexxy 4"
author = "Chloe"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dc3eaceb7f59dea41f47eb6234c2c6c37ee450fe841d4ac1bb8fe5b0ea34daa0"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
no-internal-hashes = true
